import './globals.css'
import { Inter } from 'next/font/google';

const inter = Inter({
  weight: ['400', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: 'ISCP - Integrated Supply Chain Planning',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='container'>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
